# Generated by Django 6.0.5 on 2026-06-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('kelas', models.CharField(max_length=50)),
                ('nis', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
