# Generated by Django 6.0.5 on 2026-06-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pengarang', models.CharField(blank=True, max_length=150)),
                ('kategori', models.CharField(blank=True, max_length=100)),
                ('penerbit', models.CharField(blank=True, max_length=150)),
                ('tahun', models.PositiveIntegerField(blank=True, null=True)),
                ('rak', models.CharField(blank=True, max_length=50)),
                ('stok', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
