# Generated by Django 6.0.5 on 2026-06-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_buku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peminjam', models.CharField(max_length=150)),
                ('buku', models.CharField(max_length=255)),
                ('tanggal_pinjam', models.DateField()),
                ('jatuh_tempo', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('petugas', models.CharField(max_length=150)),
                ('status', models.CharField(default='Dipinjam', max_length=30)),
            ],
        ),
    ]
