# Generated by Django 6.0.5 on 2026-06-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_peminjaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='deskripsi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
